import { Language } from "../i18n/config";

export interface ReviewMock {
  id: string;
  userName: string;
  rating: number;
  date: string;
  comment: string;
  helpfulCount: number;
}

export interface DetailedProductMock {
  id: string;
  slug: string;
  name: string;
  brand: string;
  categorySlug: string;
  subcategorySlug?: string;
  categoryName: string;
  storeName: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  imageUrl: string;
  galleryImages: string[];
  badges?: {
    bestseller?: boolean;
    fastDelivery?: boolean;
    freeShipping?: boolean;
    coupon?: string;
    campaign?: string;
    limitedStock?: boolean;
  };
  attributes?: {
    color?: string[];
    sizes?: string[];
    material?: string;
    warranty?: string;
  };
  description: string;
  specifications: Record<string, string>;
  stock: number;
  reviews: ReviewMock[];
}

export function mapDbProductToMock(dbProd: any, lang: Language = "tr"): DetailedProductMock {
  const isEn = lang === "en";

  let colors: string[] = [];
  let sizes: string[] = [];
  let images: string[] = [dbProd.imageUrl];

  try {
    if (typeof dbProd.colors === "string") colors = JSON.parse(dbProd.colors);
    if (typeof dbProd.sizes === "string") sizes = JSON.parse(dbProd.sizes);
    if (typeof dbProd.images === "string") images = JSON.parse(dbProd.images);
    if (images.length === 0) images = [dbProd.imageUrl];
  } catch (e) {}

  return {
    id: dbProd.id,
    slug: dbProd.slug,
    name: dbProd.name,
    brand: dbProd.brand || "Cadde Store",
    categorySlug: dbProd.category?.slug || "women",
    subcategorySlug: dbProd.subcategorySlug || "dresses",
    categoryName: isEn ? dbProd.category?.nameEN || dbProd.category?.nameTR : dbProd.category?.nameTR || "Kadın Giyim",
    storeName: dbProd.seller?.storeName || "Trend Fashion Mağazası",
    price: dbProd.price,
    originalPrice: dbProd.originalPrice || undefined,
    rating: dbProd.rating || 4.8,
    reviewCount: dbProd.reviewCount || 120,
    imageUrl: dbProd.imageUrl,
    galleryImages: images,
    badges: {
      bestseller: dbProd.rating >= 4.8,
      fastDelivery: true,
      freeShipping: dbProd.price >= 200,
    },
    attributes: {
      color: colors,
      sizes,
    },
    description: dbProd.description || dbProd.name,
    specifications: {
      [isEn ? "Brand" : "Marka"]: dbProd.brand || "Cadde Store",
      [isEn ? "SKU" : "Stok Kodu"]: dbProd.sku || "CS-SKU",
    },
    stock: dbProd.stock,
    reviews: Array.isArray(dbProd.reviews)
      ? dbProd.reviews.map((r: any) => ({
          id: r.id,
          userName: r.user ? `${r.user.firstName} ${r.user.lastName[0]}.` : "Müşteri",
          rating: r.rating,
          date: new Date(r.createdAt).toLocaleDateString("tr-TR"),
          comment: r.comment,
          helpfulCount: 0,
        }))
      : [],
  };
}

export function getFullCatalog(lang: Language = "tr"): DetailedProductMock[] {
  const isEn = lang === "en";

  return [
    // --- WOMEN CATEGORY (10 Products across subcategories) ---
    {
      id: "w1",
      slug: "zara-desenli-sifon-elbise-bordo",
      name: isEn ? "Chiffon Patterned Midi Dress - Burgundy" : "Desenli Şifon Midi Elbise - Bordo",
      brand: "Zara",
      categorySlug: "women",
      subcategorySlug: "dresses",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 799.90,
      originalPrice: 1199.90,
      rating: 4.9,
      reviewCount: 420,
      imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Burgundy" : "Bordo"], sizes: ["S", "M", "L"] },
      description: isEn ? "Elegant chiffon patterned midi dress for summer and autumn." : "Zarif şifon kumaş, belden oturtmalı şık midi elbise.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "%100 Şifon" },
      stock: 35,
      reviews: [{ id: "rw1", userName: "Ayşe B.", rating: 5, date: "10.08.2026", comment: "Kumaşı ve duruşu harika!", helpfulCount: 12 }],
    },
    {
      id: "w2",
      slug: "mango-kemerli-keten-elbise-krem",
      name: isEn ? "Belted Linen Casual Dress - Cream" : "Kemerli Keten Günlük Elbise - Krem",
      brand: "Mango",
      categorySlug: "women",
      subcategorySlug: "dresses",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 899.00,
      originalPrice: 1299.00,
      rating: 4.8,
      reviewCount: 310,
      imageUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Cream" : "Krem"], sizes: ["S", "M", "L"] },
      description: isEn ? "Natural breathable linen dress with matching waist belt." : "Doğal ve nefes alabilen keten kumaş, şık kemer detaylı günlük elbise.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "%100 Keten" },
      stock: 28,
      reviews: [],
    },
    {
      id: "w3",
      slug: "zara-oversize-pamuklu-kadin-tisort-beyaz",
      name: isEn ? "Oversize Pure Cotton Women's T-Shirt - White" : "Oversize %100 Pamuk Kadın Tişört - Beyaz",
      brand: "Zara",
      categorySlug: "women",
      subcategorySlug: "tshirts",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 299.99,
      originalPrice: 399.99,
      rating: 4.7,
      reviewCount: 540,
      imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"], sizes: ["XS", "S", "M", "L"] },
      description: isEn ? "Basic cotton t-shirt for daily comfort." : "%100 pamuk penye kumaş basic günlük rahat tişört.",
      specifications: { [isEn ? "Fabric" : "Kumaş"]: "%100 Pamuk" },
      stock: 50,
      reviews: [],
    },
    {
      id: "w4",
      slug: "stradivarius-baski-detayli-oversize-tisort",
      name: isEn ? "Graphic Printed Streetwear T-Shirt" : "Baskılı Oversize Sokak Modası Tişört",
      brand: "Stradivarius",
      categorySlug: "women",
      subcategorySlug: "tshirts",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 349.90,
      originalPrice: 449.90,
      rating: 4.8,
      reviewCount: 220,
      imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["S", "M", "L"] },
      description: isEn ? "Trendy printed oversize t-shirt for modern style." : "Trend vintage grafik baskılı rahat kesim tişört.",
      specifications: { [isEn ? "Fit" : "Kalıp"]: "Oversize" },
      stock: 40,
      reviews: [],
    },
    {
      id: "w5",
      slug: "mango-kurvazye-yaka-bluz-siyah",
      name: isEn ? "Cross-Front Satin Wrap Blouse - Black" : "Kurvazye Yaka Saten Bluz - Siyah",
      brand: "Mango",
      categorySlug: "women",
      subcategorySlug: "tshirts",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 549.90,
      originalPrice: 749.90,
      rating: 4.8,
      reviewCount: 180,
      imageUrl: "https://images.unsplash.com/photo-1551163943-3f6a855d1153?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1551163943-3f6a855d1153?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["S", "M", "L"] },
      description: isEn ? "Chic satin wrap blouse for evening wear." : "Şık gece ve iş kombini için saten dökümlü bluz.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "Saten" },
      stock: 22,
      reviews: [],
    },
    {
      id: "w6",
      slug: "pullbear-kase-kadin-kisa-ceket-kahverengi",
      name: isEn ? "Cropped Wool Blend Jacket - Brown" : "Kaşe Kadın Kısa Ceket - Kahverengi",
      brand: "Pull&Bear",
      categorySlug: "women",
      subcategorySlug: "jackets",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1499.00,
      originalPrice: 1999.00,
      rating: 4.9,
      reviewCount: 390,
      imageUrl: "https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Brown" : "Kahverengi"], sizes: ["S", "M", "L"] },
      description: isEn ? "Warm wool blend cropped jacket." : "Sıcak tutan yumuşak kaşe dokulu crop ceket.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "Kaşe Yün Karışım" },
      stock: 19,
      reviews: [],
    },
    {
      id: "w7",
      slug: "zara-deri-gorunumlu-biker-ceket-siyah",
      name: isEn ? "Faux Leather Biker Jacket - Black" : "Suni Deri Biker Ceket - Siyah",
      brand: "Zara",
      categorySlug: "women",
      subcategorySlug: "jackets",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1899.90,
      originalPrice: 2499.90,
      rating: 4.9,
      reviewCount: 610,
      imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["S", "M", "L"] },
      description: isEn ? "Classic biker leather jacket with zip details." : "Fermuar detaylı klasik kesim suni deri biker mont.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "Suni Deri" },
      stock: 15,
      reviews: [],
    },
    {
      id: "w8",
      slug: "bershka-yuksek-bel-wide-leg-jean-pantolon",
      name: isEn ? "High-Waist Wide Leg Denim Jeans" : "Yüksek Bel Wide Leg Denim Pantolon",
      brand: "Bershka",
      categorySlug: "women",
      subcategorySlug: "dresses",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 899.90,
      originalPrice: 1199.90,
      rating: 4.8,
      reviewCount: 480,
      imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Blue" : "Mavi"], sizes: ["34", "36", "38", "40"] },
      description: isEn ? "High waisted vintage blue wide leg jeans." : "Trend geniş paça vintage yıkamalı kot pantolon.",
      specifications: { [isEn ? "Denim" : "Kumaş"]: "%100 Pamuk Denim" },
      stock: 30,
      reviews: [],
    },
    {
      id: "w9",
      slug: "mango-triko-hırka-ve-atlet-takim-ekru",
      name: isEn ? "Knit Cardigan & Tank Top Set - Ecru" : "Triko Hırka ve Atlet İkili Takım - Ekru",
      brand: "Mango",
      categorySlug: "women",
      subcategorySlug: "dresses",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 699.90,
      originalPrice: 899.90,
      rating: 4.7,
      reviewCount: 140,
      imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Ecru" : "Ekru"], sizes: ["S", "M", "L"] },
      description: isEn ? "Cozy knitwear twin set for autumn." : "Sonbahar sezonu yumuşak dokulu triko ikili takım.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "Triko" },
      stock: 25,
      reviews: [],
    },
    {
      id: "w10",
      slug: "zara-pileli-midi-etek-siyah",
      name: isEn ? "Pleated High-Waist Midi Skirt - Black" : "Pileli Yüksek Bel Midi Etek - Siyah",
      brand: "Zara",
      categorySlug: "women",
      subcategorySlug: "dresses",
      categoryName: isEn ? "Women's Clothing" : "Kadın Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 649.90,
      originalPrice: 849.90,
      rating: 4.8,
      reviewCount: 270,
      imageUrl: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["S", "M", "L"] },
      description: isEn ? "Classic black pleated midi skirt." : "A-kesim zarif pileli siyah midi etek.",
      specifications: { [isEn ? "Pattern" : "Desen"]: "Pileli" },
      stock: 20,
      reviews: [],
    },

    // --- MEN CATEGORY (10 Products across subcategories) ---
    {
      id: "m1",
      slug: "zara-siyah-oversize-fit-bisiklet-yaka-pamuklu-erkek-tisort",
      name: isEn ? "Black Oversize Fit Crew Neck Cotton Men's T-Shirt" : "Siyah Oversize Fit Bisiklet Yaka Pamuklu Erkek Tişört",
      brand: "Zara",
      categorySlug: "men",
      subcategorySlug: "tshirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 349.99,
      originalPrice: 499.99,
      rating: 4.8,
      reviewCount: 1420,
      imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["S", "M", "L", "XL"] },
      description: isEn ? "100% premium combed cotton oversize t-shirt." : "%100 penyeden üretilmiş oversize fit tişört.",
      specifications: { [isEn ? "Fabric" : "Kumaş"]: "%100 Pamuk" },
      stock: 45,
      reviews: [],
    },
    {
      id: "m2",
      slug: "massimo-dutti-keten-uzun-kol-gomlek-mavi",
      name: isEn ? "100% Pure Linen Long Sleeve Shirt - Sky Blue" : "%100 Keten Uzun Kollu Erkek Gömlek - Gök Mavi",
      brand: "Massimo Dutti",
      categorySlug: "men",
      subcategorySlug: "shirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1299.00,
      originalPrice: 1699.00,
      rating: 4.9,
      reviewCount: 310,
      imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Blue" : "Mavi"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Luxury Italian cut pure linen long sleeve shirt." : "İtalyan kesim %100 nefes alan saf keten erkek gömlek.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "%100 Keten" },
      stock: 22,
      reviews: [],
    },
    {
      id: "m3",
      slug: "zara-slim-fit-chino-pantolon-lacivert",
      name: isEn ? "Slim Fit Cotton Chino Trousers - Navy" : "Slim Fit Pamuklu Chino Pantolon - Lacivert",
      brand: "Zara",
      categorySlug: "men",
      subcategorySlug: "trousers",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 899.90,
      originalPrice: 1199.90,
      rating: 4.8,
      reviewCount: 450,
      imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Navy" : "Lacivert"], sizes: ["30", "32", "34", "36"] },
      description: isEn ? "Stretchy comfortable slim fit chinos." : "Esnek gabardin kumaş slim fit lacivert pantolon.",
      specifications: { [isEn ? "Fit" : "Kalıp"]: "Slim Fit" },
      stock: 30,
      reviews: [],
    },
    {
      id: "m4",
      slug: "nike-sportswear-hoodie-sweatshirt-gri",
      name: isEn ? "Club Fleece Hooded Sweatshirt - Grey" : "Club Fleece Kapüşonlu Sweatshirt - Gri",
      brand: "Nike",
      categorySlug: "men",
      subcategorySlug: "sweatshirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 1599.90,
      originalPrice: 1999.90,
      rating: 4.9,
      reviewCount: 890,
      imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Grey" : "Gri"], sizes: ["S", "M", "L", "XL"] },
      description: isEn ? "Soft fleece comfortable everyday hoodie." : "İçi şardonlu yumuşak rahat kapüşonlu sweatshirt.",
      specifications: { [isEn ? "Fleece" : "Kumaş"]: "Şardonlu Pamuk" },
      stock: 25,
      reviews: [],
    },
    {
      id: "m5",
      slug: "pullbear-sisi-sme-mont-siyah",
      name: isEn ? "Puffer Winter Jacket - Black" : "Şişme Kışlık Mont - Siyah",
      brand: "Pull&Bear",
      categorySlug: "men",
      subcategorySlug: "jackets",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1999.00,
      originalPrice: 2599.00,
      rating: 4.8,
      reviewCount: 340,
      imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Water resistant warm puffer jacket." : "Su geçirmez rüzgar korumalı sıcak tutan şişme mont.",
      specifications: { [isEn ? "Waterproof" : "Su Geçirmezlik"]: "Evet" },
      stock: 14,
      reviews: [],
    },
    {
      id: "m6",
      slug: "lacoste-polo-yaka-tisort-yesil",
      name: isEn ? "Classic Cotton Polo Shirt - Green" : "Klasik Pamuklu Polo Yaka Tişört - Yeşil",
      brand: "Lacoste",
      categorySlug: "men",
      subcategorySlug: "tshirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1799.90,
      originalPrice: 2299.90,
      rating: 4.9,
      reviewCount: 510,
      imageUrl: "https://images.unsplash.com/photo-1625910513413-562725e839e1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1625910513413-562725e839e1?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Green" : "Yeşil"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Original pique cotton classic polo." : "%100 pike pamuk ikonik yeşil timsah nakışlı polo tişört.",
      specifications: { [isEn ? "Pique" : "Kumaş"]: "Pike Pamuk" },
      stock: 18,
      reviews: [],
    },
    {
      id: "m7",
      slug: "levis-501-original-fit-jean-pantolon",
      name: isEn ? "501 Original Fit Straight Jeans" : "501 Original Fit Düz Kesim Kot Pantolon",
      brand: "Levi's",
      categorySlug: "men",
      subcategorySlug: "trousers",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1899.00,
      originalPrice: 2399.00,
      rating: 4.9,
      reviewCount: 780,
      imageUrl: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Blue" : "Mavi"], sizes: ["30", "32", "34"] },
      description: isEn ? "Iconic straight fit denim jeans." : "Efsanevi düz kesim %100 pamuk denim jean.",
      specifications: { [isEn ? "Fit" : "Kalıp"]: "Straight Fit" },
      stock: 20,
      reviews: [],
    },
    {
      id: "m8",
      slug: "zara-kareli-oduncu-gomlegi",
      name: isEn ? "Plaid Cotton Flannel Shirt" : "Kareli Pamuklu Oduncu Gömleği",
      brand: "Zara",
      categorySlug: "men",
      subcategorySlug: "shirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 699.90,
      originalPrice: 899.90,
      rating: 4.7,
      reviewCount: 230,
      imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Red" : "Kırmızı"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Cozy flannel check shirt." : "Kış ve sonbahar için yumuşak flanel oduncu gömleği.",
      specifications: { [isEn ? "Flannel" : "Kumaş"]: "Pamuk Flanel" },
      stock: 28,
      reviews: [],
    },
    {
      id: "m9",
      slug: "adidas-3-stripes-fermuarli-hırka",
      name: isEn ? "3-Stripes Track Zip Hoodie - Black" : "3-Stripes Fermuarlı Spor Hırka - Siyah",
      brand: "Adidas",
      categorySlug: "men",
      subcategorySlug: "sweatshirts",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 1799.00,
      originalPrice: 2199.00,
      rating: 4.8,
      reviewCount: 410,
      imageUrl: "https://images.unsplash.com/photo-1578768079052-aa76e52ffe62?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1578768079052-aa76e52ffe62?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Classic 3-Stripes zip jacket." : "İkonik 3 bantlı tam boy fermuarlı spor hırka.",
      specifications: { [isEn ? "Sport" : "Kullanım"]: "Spor & Günlük" },
      stock: 16,
      reviews: [],
    },
    {
      id: "m10",
      slug: "massimo-dutti-deri-ceket-siyah",
      name: isEn ? "Genuine Sheepskin Leather Jacket - Black" : "Hakiki Kuzu Derisi Erkek Ceket - Siyah",
      brand: "Massimo Dutti",
      categorySlug: "men",
      subcategorySlug: "jackets",
      categoryName: isEn ? "Men's Clothing" : "Erkek Giyim",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 4999.00,
      originalPrice: 6499.00,
      rating: 5.0,
      reviewCount: 190,
      imageUrl: "https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["M", "L", "XL"] },
      description: isEn ? "Luxury premium sheepskin leather jacket." : "%100 hakiki yumuşak kuzu derisi lüks erkek mont.",
      specifications: { [isEn ? "Leather" : "Deri Tipi"]: "Hakiki Kuzu Derisi" },
      stock: 8,
      reviews: [],
    },

    // --- ELECTRONICS CATEGORY (10 Products across subcategories) ---
    {
      id: "e1",
      slug: "apple-iphone-15-pro-max-256gb-dogal-titanyum",
      name: isEn ? "iPhone 15 Pro Max 256GB - Natural Titanium" : "iPhone 15 Pro Max 256GB - Doğal Titanyum",
      brand: "Apple",
      categorySlug: "electronics",
      subcategorySlug: "smartphones",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 74999.00,
      originalPrice: 79999.00,
      rating: 4.9,
      reviewCount: 2450,
      imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Natural Titanium" : "Doğal Titanyum"] },
      description: isEn ? "A17 Pro chip, titanium design, 48MP camera." : "A17 Pro çip, titanyum tasarım, 48MP ana kamera ve Eylem Butonu.",
      specifications: { [isEn ? "Storage" : "Hafıza"]: "256 GB" },
      stock: 12,
      reviews: [],
    },
    {
      id: "e2",
      slug: "samsung-galaxy-s24-ultra-512gb-titanyum-siyah",
      name: isEn ? "Galaxy S24 Ultra 512GB AI Smartphone" : "Galaxy S24 Ultra 512GB Yapay Zeka Telefon",
      brand: "Samsung",
      categorySlug: "electronics",
      subcategorySlug: "smartphones",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 68999.00,
      originalPrice: 74999.00,
      rating: 4.9,
      reviewCount: 1820,
      imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Titanium Black" : "Titanyum Siyah"] },
      description: isEn ? "Galaxy AI, 200MP camera, built-in S Pen." : "Entegre S Pen, 200 MP kamera ve Galaxy AI yapay zeka özellikleri.",
      specifications: { [isEn ? "RAM" : "RAM"]: "12 GB" },
      stock: 15,
      reviews: [],
    },
    {
      id: "e3",
      slug: "sony-wh-1000xm5-kablosuz-kulaklik",
      name: isEn ? "WH-1000XM5 Wireless ANC Headphones" : "WH-1000XM5 Kablosuz Gürültü Engelleme Kulaklık",
      brand: "Sony",
      categorySlug: "electronics",
      subcategorySlug: "headphones",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 11999.00,
      originalPrice: 13999.00,
      rating: 4.8,
      reviewCount: 950,
      imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Industry leading noise canceling over ear headphones." : "Sektör lideri aktif gürültü engelleme ve 30 saat pil ömrü.",
      specifications: { [isEn ? "Battery" : "Pil"]: "30 Saat" },
      stock: 20,
      reviews: [],
    },
    {
      id: "e4",
      slug: "apple-airpods-pro-2-nesil-usb-c",
      name: isEn ? "AirPods Pro (2nd Gen) USB-C ANC Earbuds" : "AirPods Pro (2. Nesil) USB-C Kulak İçi Kulaklık",
      brand: "Apple",
      categorySlug: "electronics",
      subcategorySlug: "headphones",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 8499.00,
      originalPrice: 9499.00,
      rating: 4.9,
      reviewCount: 3120,
      imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"] },
      description: isEn ? "Active noise cancellation and Adaptive Audio." : "Aktif gürültü engelleme ve Şeffaf Mod destekli MagSafe kutulu kulaklık.",
      specifications: { [isEn ? "Chip" : "Çip"]: "Apple H2" },
      stock: 35,
      reviews: [],
    },
    {
      id: "e5",
      slug: "apple-macbook-pro-14-m3-pro-18gb-512gb",
      name: isEn ? "MacBook Pro 14\" M3 Pro 18GB RAM 512GB SSD" : "MacBook Pro 14\" M3 Pro 18GB RAM 512GB SSD",
      brand: "Apple",
      categorySlug: "electronics",
      subcategorySlug: "laptops",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 72999.00,
      originalPrice: 78999.00,
      rating: 5.0,
      reviewCount: 410,
      imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Space Black" : "Uzay Siyahı"] },
      description: isEn ? "Liquid Retina XDR display with M3 Pro chip." : "M3 Pro işlemci, Liquid Retina XDR ekran ve 18 saat pil ömrü.",
      specifications: { [isEn ? "RAM" : "Bellek"]: "18 GB" },
      stock: 9,
      reviews: [],
    },
    {
      id: "e6",
      slug: "asus-rog-strix-g16-i7-4070-gaming-laptop",
      name: isEn ? "ROG Strix G16 i7 RTX 4070 Gaming Laptop" : "ROG Strix G16 i7 RTX 4070 Oyuncu Bilgisayarı",
      brand: "Asus",
      categorySlug: "electronics",
      subcategorySlug: "laptops",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 59999.00,
      originalPrice: 65999.00,
      rating: 4.8,
      reviewCount: 290,
      imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "165Hz ROG Nebula Display with RTX 4070." : "NVIDIA GeForce RTX 4070 ekran kartlı 165Hz e-spor oyuncu laptopu.",
      specifications: { [isEn ? "GPU" : "Ekran Kartı"]: "RTX 4070 8GB" },
      stock: 11,
      reviews: [],
    },
    {
      id: "e7",
      slug: "lg-65-inch-oled-4k-smart-tv-c3",
      name: isEn ? "LG 65\" OLED evo 4K Smart TV C3 Series" : "LG 65\" OLED evo 4K Smart TV C3 Serisi",
      brand: "LG",
      categorySlug: "electronics",
      subcategorySlug: "tvs",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 64999.00,
      originalPrice: 72999.00,
      rating: 4.9,
      reviewCount: 380,
      imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Self-lit OLED pixels with 120Hz gaming support." : "Sonsuz kontrast, Dolby Vision ve 120Hz HDMI 2.1 oyun desteği.",
      specifications: { [isEn ? "Screen Size" : "Ekran Boyutu"]: "65 Inç / 165 cm" },
      stock: 6,
      reviews: [],
    },
    {
      id: "e8",
      slug: "apple-watch-ultra-2-titanyum-gps-cellular",
      name: isEn ? "Apple Watch Ultra 2 GPS + Cellular Titanium" : "Apple Watch Ultra 2 GPS + Cellular Titanyum",
      brand: "Apple",
      categorySlug: "electronics",
      subcategorySlug: "smartwatches",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 38999.00,
      originalPrice: 42999.00,
      rating: 4.9,
      reviewCount: 520,
      imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Titanium" : "Titanyum"] },
      description: isEn ? "Rugged titanium smartwatch with 100m water resistance." : "Titanyum kasa, 3000 nit safir ekran ve 100m su geçirmezlik.",
      specifications: { [isEn ? "Water Resistance" : "Su Geçirmezlik"]: "100 Metre" },
      stock: 14,
      reviews: [],
    },
    {
      id: "e9",
      slug: "samsung-55-inch-qled-4k-smart-tv",
      name: isEn ? "Samsung 55\" QLED 4K Smart TV Q60C" : "Samsung 55\" QLED 4K Smart TV Q60C",
      brand: "Samsung",
      categorySlug: "electronics",
      subcategorySlug: "tvs",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 29999.00,
      originalPrice: 34999.00,
      rating: 4.7,
      reviewCount: 640,
      imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Quantum Dot 100% color volume 4K QLED TV." : "%100 Renk Hacimli Quantum Dot QLED 4K Akıllı TV.",
      specifications: { [isEn ? "Panel" : "Panel"]: "QLED 4K" },
      stock: 10,
      reviews: [],
    },
    {
      id: "e10",
      slug: "xiaomi-robot-vacuum-s10-plus-akilli-robot-suburge",
      name: isEn ? "Xiaomi Robot Vacuum S10+ Robot Mop" : "Xiaomi Robot Vacuum S10+ Akıllı Robot Süpürge",
      brand: "Xiaomi",
      categorySlug: "electronics",
      subcategorySlug: "smartphones",
      categoryName: isEn ? "Electronics" : "Elektronik",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 13999.00,
      originalPrice: 16999.00,
      rating: 4.8,
      reviewCount: 1280,
      imageUrl: "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"] },
      description: isEn ? "4000Pa suction with dual rotary mopping pads." : "4000Pa güçlü emiş gücü ve çift döner paspaslama teknolojisi.",
      specifications: { [isEn ? "Suction" : "Emiş Gücü"]: "4000 Pa" },
      stock: 25,
      reviews: [],
    },

    // --- SHOES & BAGS CATEGORY (10 Products across subcategories) ---
    {
      id: "sb1",
      slug: "nike-air-cushion-kosu-ve-yuruyus-spor-ayakkabisi",
      name: isEn ? "Air Cushion Running & Walking Sports Shoes" : "Air Cushion Koşu ve Yürüyüş Spor Ayakkabısı",
      brand: "Nike",
      categorySlug: "shoes-bags",
      subcategorySlug: "sneakers",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 2199.00,
      originalPrice: 2899.00,
      rating: 4.9,
      reviewCount: 3840,
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Red" : "Kırmızı"], sizes: ["40", "41", "42", "43"] },
      description: isEn ? "High-performance air-cushioned running shoes." : "Özel hava yastıklı koşu ayakkabısı.",
      specifications: { [isEn ? "Sole" : "Taban"]: "Air Cushion" },
      stock: 18,
      reviews: [],
    },
    {
      id: "sb2",
      slug: "adidas-stan-smith-deri-beyaz-sneaker",
      name: isEn ? "Stan Smith Leather Casual Sneakers - White" : "Stan Smith Hakiki Deri Beyaz Sneaker",
      brand: "Adidas",
      categorySlug: "shoes-bags",
      subcategorySlug: "sneakers",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 2499.00,
      originalPrice: 2999.00,
      rating: 4.9,
      reviewCount: 2910,
      imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"], sizes: ["38", "39", "40", "41", "42"] },
      description: isEn ? "Iconic tennis classic leather sneakers." : "Efsanevi tenis klasiği hakiki deri beyaz günlük ayakkabı.",
      specifications: { [isEn ? "Upper" : "Dış Malzeme"]: "Hakiki Deri" },
      stock: 30,
      reviews: [],
    },
    {
      id: "sb3",
      slug: "michael-kors-hakiki-deri-omuz-cantasi-siyah",
      name: isEn ? "Jet Set Genuine Leather Shoulder Bag - Black" : "Jet Set Hakiki Deri Kadın Omuz Çantası - Siyah",
      brand: "Michael Kors",
      categorySlug: "shoes-bags",
      subcategorySlug: "bags",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 4899.00,
      originalPrice: 6299.00,
      rating: 4.9,
      reviewCount: 620,
      imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Luxury Saffiano leather shoulder bag with gold hardware." : "Gold detaylı şık Saffiano hakiki deri omuz çantası.",
      specifications: { [isEn ? "Leather" : "Deri"]: "Hakiki Saffiano Deri" },
      stock: 12,
      reviews: [],
    },
    {
      id: "sb4",
      slug: "timberland-6-inch-su-gecirmez-deri-bot-taba",
      name: isEn ? "6-Inch Premium Waterproof Leather Boots - Tan" : "6-Inch Premium Su Geçirmez Deri Bot - Taba",
      brand: "Timberland",
      categorySlug: "shoes-bags",
      subcategorySlug: "boots",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 5499.00,
      originalPrice: 6499.00,
      rating: 5.0,
      reviewCount: 1120,
      imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Tan" : "Taba Sarı"], sizes: ["41", "42", "43", "44"] },
      description: isEn ? "Iconic waterproof nubuck winter boots." : "Su geçirmez nubuk deri ikonik kışlık bot.",
      specifications: { [isEn ? "Waterproof" : "Su Geçirmezlik"]: "Evet" },
      stock: 14,
      reviews: [],
    },
    {
      id: "sb5",
      slug: "stiletto-topuklu-ayakkabi-siyah-rugan",
      name: isEn ? "Patent Leather High Heel Stilettos - Black" : "Rugan Yüksek Topuklu Stiletto - Siyah",
      brand: "Zara",
      categorySlug: "shoes-bags",
      subcategorySlug: "heels",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 999.90,
      originalPrice: 1399.90,
      rating: 4.8,
      reviewCount: 380,
      imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black Patent" : "Siyah Rugan"], sizes: ["36", "37", "38", "39"] },
      description: isEn ? "Elegant 9cm patent high heels for formal occasions." : "9 cm ince topuklu şık siyah rugan stiletto ayakkabı.",
      specifications: { [isEn ? "Heel Height" : "Topuk Boyu"]: "9 cm" },
      stock: 22,
      reviews: [],
    },
    {
      id: "sb6",
      slug: "converse-chuck-taylor-all-star-high-top",
      name: isEn ? "Chuck Taylor All Star High-Top Canvas Sneakers" : "Chuck Taylor All Star Yüksek Taban Bez Sneaker",
      brand: "Converse",
      categorySlug: "shoes-bags",
      subcategorySlug: "sneakers",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 1899.90,
      originalPrice: 2299.90,
      rating: 4.9,
      reviewCount: 1780,
      imageUrl: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"], sizes: ["37", "38", "39", "40", "41"] },
      description: isEn ? "Classic retro canvas high top sneakers." : "Klasik ikonik yüksek bilekli bez sneaker ayakkabı.",
      specifications: { [isEn ? "Material" : "Kumaş"]: "Kanvas Bez" },
      stock: 40,
      reviews: [],
    },
    {
      id: "sb7",
      slug: "zara-kapitone-zincirli-capraz-canta-krem",
      name: isEn ? "Quilted Chain Crossbody Bag - Cream" : "Kapitone Zincir Askılı Çapraz Çanta - Krem",
      brand: "Zara",
      categorySlug: "shoes-bags",
      subcategorySlug: "bags",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 699.90,
      originalPrice: 999.90,
      rating: 4.7,
      reviewCount: 420,
      imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Cream" : "Krem"] },
      description: isEn ? "Quilted elegant crossbody bag with gold strap." : "Altın renk zincir askılı şık kapitone kadın çantası.",
      specifications: { [isEn ? "Style" : "Stil"]: "Çapraz Çanta" },
      stock: 25,
      reviews: [],
    },
    {
      id: "sb8",
      slug: "harley-davidson-hakiki-deri-suet-bot",
      name: isEn ? "Genuine Leather Biker Boots - Dark Brown" : "Hakiki Deri Kovboy Biker Bot - Koyu Kahve",
      brand: "Harley Davidson",
      categorySlug: "shoes-bags",
      subcategorySlug: "boots",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 3999.00,
      originalPrice: 4999.00,
      rating: 4.9,
      reviewCount: 560,
      imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Dark Brown" : "Koyu Kahve"], sizes: ["40", "41", "42", "43"] },
      description: isEn ? "Rugged heavy duty genuine leather boots." : "Tokalı dayanıklı ağır kış şartlarına uygun hakiki deri bot.",
      specifications: { [isEn ? "Leather" : "Deri"]: "Hakiki Deri" },
      stock: 16,
      reviews: [],
    },
    {
      id: "sb9",
      slug: "puma-carina-street-kadin-sneaker-beyaz",
      name: isEn ? "Carina Street Women's Platform Sneakers" : "Carina Street Kadın Yüksek Taban Sneaker",
      brand: "Puma",
      categorySlug: "shoes-bags",
      subcategorySlug: "sneakers",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "Sports Market Turkey" : "Spor Market Türkiye",
      price: 1999.90,
      originalPrice: 2499.90,
      rating: 4.8,
      reviewCount: 890,
      imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"], sizes: ["36", "37", "38", "39"] },
      description: isEn ? "SoftFoam+ comfort padded platform sneakers." : "SoftFoam+ konfor iç tabanlı yüksek kalın taban beyaz kadın ayakkabı.",
      specifications: { [isEn ? "Sole" : "Taban"]: "Platform Kauçuk" },
      stock: 28,
      reviews: [],
    },
    {
      id: "sb10",
      slug: "samsonite-laptop-sirt-cantasi-siyah",
      name: isEn ? "Pro-DLX 15.6\" Business Laptop Backpack" : "Pro-DLX 15.6\" Su Geçirmez İş & Laptop Sırt Çantası",
      brand: "Samsonite",
      categorySlug: "shoes-bags",
      subcategorySlug: "bags",
      categoryName: isEn ? "Shoes & Bags" : "Ayakkabı & Çanta",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 3499.00,
      originalPrice: 4299.00,
      rating: 4.9,
      reviewCount: 340,
      imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Ergonomic water-repellent business laptop backpack." : "Ortopedik korumalı su geçirmez korumalı laptop çantası.",
      specifications: { [isEn ? "Capacity" : "Kapasite"]: "24 Litre" },
      stock: 18,
      reviews: [],
    },

    // --- HOME & LIVING CATEGORY (10 Products across subcategories) ---
    {
      id: "h1",
      slug: "karaca-biogranit-7-parca-tencere-seti-gri",
      name: isEn ? "BioGranite 7-Piece Cookware Set - Grey" : "BioGranite 7 Parça Tencere Tava Seti - Gri",
      brand: "Karaca",
      categorySlug: "home-living",
      subcategorySlug: "cookware",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "Karaca Official Store" : "Karaca Resmi Mağazası",
      price: 1899.00,
      originalPrice: 2499.00,
      rating: 4.8,
      reviewCount: 1650,
      imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Grey Granite" : "Gri Granit"] },
      description: isEn ? "Non-stick granite coating 7-piece cookware set." : "Çizilmeye karşı ekstra dayanıklı 7 parça biogranit tencere takımı.",
      specifications: { [isEn ? "Pieces" : "Parça Sayısı"]: "7 Parça" },
      stock: 35,
      reviews: [],
    },
    {
      id: "h2",
      slug: "philips-airfryer-xxl-sicak-hava-fritozu",
      name: isEn ? "Airfryer XXL Smart Sensing Hot Air Fryer" : "Airfryer XXL Akıllı Sıcak Hava Fritözü",
      brand: "Philips",
      categorySlug: "home-living",
      subcategorySlug: "airfryers",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 6999.00,
      originalPrice: 8499.00,
      rating: 4.9,
      reviewCount: 4210,
      imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "FatRemoval technology 1.4kg capacity hot air fryer." : "Rapid Air teknolojisi ile %90 daha az yağlı sağlıklı kızartma.",
      specifications: { [isEn ? "Capacity" : "Kapasite"]: "1.4 kg / 7.2 L" },
      stock: 20,
      reviews: [],
    },
    {
      id: "h3",
      slug: "nespresso-essenza-mini-kahve-makinesi",
      name: isEn ? "Essenza Mini Espresso Coffee Machine - Red" : "Essenza Mini Kapsüllü Espresso Kahve Makinesi - Kırmızı",
      brand: "Nespresso",
      categorySlug: "home-living",
      subcategorySlug: "cookware",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 4299.00,
      originalPrice: 4999.00,
      rating: 4.9,
      reviewCount: 980,
      imageUrl: "https://images.unsplash.com/photo-1517668808822-9e428d690a81?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1517668808822-9e428d690a81?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Red" : "Kırmızı"] },
      description: isEn ? "Compact 19-bar high pressure capsule coffee machine." : "19 bar basınçlı ultra kompakt kapsüllü kahve makinesi.",
      specifications: { [isEn ? "Pressure" : "Basınç"]: "19 Bar" },
      stock: 16,
      reviews: [],
    },
    {
      id: "h4",
      slug: "karaca-home-pamuk-saten-cift-kisilik-nevresim-takimi",
      name: isEn ? "100% Cotton Satin Double Bedding Duvet Set" : "%100 Pamuk Saten Çift Kişilik Nevresim Takımı",
      brand: "Karaca Home",
      categorySlug: "home-living",
      subcategorySlug: "bedding",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "Karaca Official Store" : "Karaca Resmi Mağazası",
      price: 1299.90,
      originalPrice: 1799.90,
      rating: 4.8,
      reviewCount: 740,
      imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Soft Pink" : "Pudra Pembe"] },
      description: isEn ? "Silky smooth 100% cotton satin duvet cover set." : "Yumuşacık dökümlü pamuk saten nevresim kılıfı ve yastık takımı.",
      specifications: { [isEn ? "Fabric" : "Kumaş"]: "%100 Pamuk Saten" },
      stock: 24,
      reviews: [],
    },
    {
      id: "h5",
      slug: "tefal-fv9845-ultragliss-buharli-utu",
      name: isEn ? "Ultimate Pure 3200W Steam Iron" : "Ultimate Pure 3200W Yüksek Buharlı Ütü",
      brand: "Tefal",
      categorySlug: "home-living",
      subcategorySlug: "cookware",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 3199.00,
      originalPrice: 3899.00,
      rating: 4.8,
      reviewCount: 510,
      imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Blue" : "Mavi"] },
      description: isEn ? "Micro-calc filter 260g steam boost iron." : "Kireç avcısı filtreli 260 gr/dk şok buharlı ütü.",
      specifications: { [isEn ? "Power" : "Güç"]: "3200 Watt" },
      stock: 19,
      reviews: [],
    },
    {
      id: "h6",
      slug: "ikea-iskandinav-ahsap-zencefil-lambader",
      name: isEn ? "Scandinavian Solid Wood Floor Lamp" : "İskandinav Doğal Ahşap Gövdeli Lambader",
      brand: "IKEA",
      categorySlug: "home-living",
      subcategorySlug: "decor",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "Karaca Official Store" : "Karaca Resmi Mağazası",
      price: 899.90,
      originalPrice: 1199.90,
      rating: 4.7,
      reviewCount: 320,
      imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Natural Wood" : "Doğal Ahşap"] },
      description: isEn ? "Modern wooden tripod floor standing light." : "Salon ve yatak odası için dekoratif ahşap lambader.",
      specifications: { [isEn ? "Height" : "Yükseklik"]: "150 cm" },
      stock: 22,
      reviews: [],
    },
    {
      id: "h7",
      slug: "dyson-v15-detect-dikey-kablosuz-supurge",
      name: isEn ? "V15 Detect Absolute Cordless Vacuum Cleaner" : "V15 Detect Absolute Kablosuz Dikey Süpürge",
      brand: "Dyson",
      categorySlug: "home-living",
      subcategorySlug: "airfryers",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 24999.00,
      originalPrice: 27999.00,
      rating: 5.0,
      reviewCount: 1890,
      imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Yellow Nickel" : "Sarı Nikel"] },
      description: isEn ? "Laser reveals microscopic dust with 240AW suction." : "Lazerli başlığı ile mikroskobik tozları gösteren 240AW emiş gücüne sahip dikey süpürge.",
      specifications: { [isEn ? "Run Time" : "Çalışma Süresi"]: "60 Dakika" },
      stock: 8,
      reviews: [],
    },
    {
      id: "h8",
      slug: "karaca-porselen-6-kisilik-fincan-takimi",
      name: isEn ? "6-Person Porcelain Turkish Coffee Cup Set" : "6 Kişilik Porselen Türk Kahvesi Fincan Takımı",
      brand: "Karaca",
      categorySlug: "home-living",
      subcategorySlug: "cookware",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "Karaca Official Store" : "Karaca Resmi Mağazası",
      price: 499.90,
      originalPrice: 699.90,
      rating: 4.9,
      reviewCount: 880,
      imageUrl: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White Gold" : "Beyaz Altın"] },
      description: isEn ? "Golden rim fine porcelain coffee set." : "Altın yaldız işlemeli fine porselen kahve fincan takımı.",
      specifications: { [isEn ? "Pieces" : "Parça"]: "12 Parça" },
      stock: 40,
      reviews: [],
    },
    {
      id: "h9",
      slug: "bravilor-bonamat-filtre-kahve-makinesi",
      name: isEn ? "Programmable Stainless Steel Filter Coffee Maker" : "Zaman Ayarlı Paslanmaz Çelik Filtre Kahve Makinesi",
      brand: "Karaca",
      categorySlug: "home-living",
      subcategorySlug: "cookware",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 1699.90,
      originalPrice: 2199.90,
      rating: 4.8,
      reviewCount: 390,
      imageUrl: "https://images.unsplash.com/photo-1517668808822-9e428d690a81?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1517668808822-9e428d690a81?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Inox" : "Inox Gri"] },
      description: isEn ? "1.2L aroma glass carafe filter coffee maker." : "1.2 litrelik cam karaf zaman ayarlı filtre kahve demleme cihazı.",
      specifications: { [isEn ? "Capacity" : "Kapasite"]: "12 Fincan" },
      stock: 21,
      reviews: [],
    },
    {
      id: "h10",
      slug: "madame-coco-pamuklu-bornoz-takimi",
      name: isEn ? "100% Cotton Premium Unisex Bathrobe Set" : "%100 Pamuk Premium Bornoz & Havlu Takımı",
      brand: "Madame Coco",
      categorySlug: "home-living",
      subcategorySlug: "bedding",
      categoryName: isEn ? "Home & Living" : "Ev & Yaşam",
      storeName: isEn ? "Karaca Official Store" : "Karaca Resmi Mağazası",
      price: 999.90,
      originalPrice: 1399.90,
      rating: 4.8,
      reviewCount: 610,
      imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "White" : "Beyaz"], sizes: ["L", "XL"] },
      description: isEn ? "Super absorbent plush cotton bathrobe set." : "Yüksek su emiciliğe sahip yumuşak pamuk bornoz seti.",
      specifications: { [isEn ? "Fabric" : "Kumaş"]: "%100 Pamuk" },
      stock: 26,
      reviews: [],
    },

    // --- BEAUTY & CARE CATEGORY (10 Products across subcategories) ---
    {
      id: "b1",
      slug: "la-roche-posay-hyalu-b5-serum-30ml",
      name: isEn ? "Hyalu B5 Anti-Aging Hyaluronic Acid Serum 30ml" : "Hyalu B5 Yaşlanma Karşıtı Saf Hyalüronik Asit Serum 30ml",
      brand: "La Roche-Posay",
      categorySlug: "beauty-care",
      subcategorySlug: "skincare",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 849.90,
      originalPrice: 1099.90,
      rating: 4.9,
      reviewCount: 2890,
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Dermatological hyaluronic acid serum for plump skin." : "Cilt dolgunlaştırıcı hyalüronik asit ve B5 vitamini içeren serum.",
      specifications: { [isEn ? "Volume" : "Hacim"]: "30 ml" },
      stock: 45,
      reviews: [],
    },
    {
      id: "b2",
      slug: "dior-sauvage-edp-erkek-parfum-100ml",
      name: isEn ? "Sauvage Eau de Parfum Men's Perfume 100ml" : "Sauvage Eau de Parfum Erkek Parfüm 100ml",
      brand: "Dior",
      categorySlug: "beauty-care",
      subcategorySlug: "perfume",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 4999.00,
      originalPrice: 5899.00,
      rating: 5.0,
      reviewCount: 1940,
      imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Iconic woody spicy fresh men's EDP fragrance." : "Taze bergamot ve odunsu notalardan oluşan efsanevi erkek parfümü.",
      specifications: { [isEn ? "Type" : "Tür"]: "EDP" },
      stock: 20,
      reviews: [],
    },
    {
      id: "b3",
      slug: "olaplex-no-3-sac-mukummelletirici-100ml",
      name: isEn ? "No. 3 Hair Perfector Repairing Treatment 100ml" : "No. 3 Hair Perfector Saç Bağ Güçlendirici Bakım 100ml",
      brand: "Olaplex",
      categorySlug: "beauty-care",
      subcategorySlug: "haircare",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 999.00,
      originalPrice: 1299.00,
      rating: 4.9,
      reviewCount: 1120,
      imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Patented bond building hair repairing treatment." : "Yıpranmış saç bağlarını onaran patentli saç bakım kürü.",
      specifications: { [isEn ? "Volume" : "Hacim"]: "100 ml" },
      stock: 30,
      reviews: [],
    },
    {
      id: "b4",
      slug: "chanel-coco-mademoiselle-edp-50ml",
      name: isEn ? "Coco Mademoiselle Eau de Parfum Women 50ml" : "Coco Mademoiselle Eau de Parfum Kadın Parfüm 50ml",
      brand: "Chanel",
      categorySlug: "beauty-care",
      subcategorySlug: "perfume",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 4499.00,
      originalPrice: 5299.00,
      rating: 4.9,
      reviewCount: 1450,
      imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Oriental floral elegant fragrance for women." : "Oryantal ve taze çiçek notalı zarafet dolu kadın parfümü.",
      specifications: { [isEn ? "Type" : "Tür"]: "EDP" },
      stock: 15,
      reviews: [],
    },
    {
      id: "b5",
      slug: "maybelline-sky-high-maskara-siyah",
      name: isEn ? "Lash Sensational Sky High Waterproof Mascara" : "Lash Sensational Sky High Su Geçirmez Maskara - Siyah",
      brand: "Maybelline",
      categorySlug: "beauty-care",
      subcategorySlug: "makeup",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 349.90,
      originalPrice: 499.90,
      rating: 4.8,
      reviewCount: 5210,
      imageUrl: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Black" : "Siyah"] },
      description: isEn ? "Unlimited length and volume mascara." : "Kirpiklerde sınır tanımayan uzunluk ve hacim etkisi veren maskara.",
      specifications: { [isEn ? "Waterproof" : "Su Geçirmez"]: "Evet" },
      stock: 50,
      reviews: [],
    },
    {
      id: "b6",
      slug: "the-ordinary-niacinamide-10-zinc-1",
      name: isEn ? "Niacinamide 10% + Zinc 1% Blemish Serum 30ml" : "Niacinamide 10% + Zinc 1% Cilt Kusursuzlaştırıcı Serum 30ml",
      brand: "The Ordinary",
      categorySlug: "beauty-care",
      subcategorySlug: "skincare",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 449.90,
      originalPrice: 599.90,
      rating: 4.8,
      reviewCount: 3400,
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Pore reducing niacinamide blemish serum." : "Gözenek sıkılaştırıcı ve cilt lekesi karşıtı serum.",
      specifications: { [isEn ? "Volume" : "Hacim"]: "30 ml" },
      stock: 40,
      reviews: [],
    },
    {
      id: "b7",
      slug: "dyson-airwrap-complete-long-sac-sekillendirici",
      name: isEn ? "Airwrap Multi-Styler Complete Long Nickel Copper" : "Airwrap Multi-Styler Saç Şekillendirici Seti Nikel Bakır",
      brand: "Dyson",
      categorySlug: "beauty-care",
      subcategorySlug: "haircare",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "TechWorld Turkey" : "TechWorld Türkiye",
      price: 21999.00,
      originalPrice: 24999.00,
      rating: 5.0,
      reviewCount: 1680,
      imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Nickel Copper" : "Nikel Bakır"] },
      description: isEn ? "Coanda air styling without extreme heat damage." : "Aşırı ısı olmadan Coanda hava akımı ile bukle, dalga ve düzleştirme.",
      specifications: { [isEn ? "Technology" : "Teknoloji"]: "Coanda Hava Akımı" },
      stock: 7,
      reviews: [],
    },
    {
      id: "b8",
      slug: "nars-radiant-creamy-concealer-vanilla",
      name: isEn ? "Radiant Creamy Concealer - Vanilla" : "Radiant Creamy Kapatıcı - Vanilla",
      brand: "NARS",
      categorySlug: "beauty-care",
      subcategorySlug: "makeup",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 1199.90,
      originalPrice: 1499.90,
      rating: 4.9,
      reviewCount: 920,
      imageUrl: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=800&q=80"],
      badges: { fastDelivery: true, freeShipping: true },
      attributes: { color: [isEn ? "Vanilla" : "Vanilla"] },
      description: isEn ? "Award winning luminous finish creamy concealer." : "Aydınlık doğal bitişli kült likit göz altı kapatıcısı.",
      specifications: { [isEn ? "Coverage" : "Kapatıcılık"]: "Orta-Yüksek" },
      stock: 22,
      reviews: [],
    },
    {
      id: "b9",
      slug: "bioderma-sensibio-h2o-micellar-su-500ml",
      name: isEn ? "Sensibio H2O Micellar Makeup Remover Water 500ml" : "Sensibio H2O Hassas Ciltler İçin Misel Su 500ml",
      brand: "Bioderma",
      categorySlug: "beauty-care",
      subcategorySlug: "skincare",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 499.90,
      originalPrice: 699.90,
      rating: 4.9,
      reviewCount: 4120,
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Dermatological cleansing water for sensitive skin." : "Hassas ciltler için durulama gerektirmeyen makyaj temizleyici misel su.",
      specifications: { [isEn ? "Volume" : "Hacim"]: "500 ml" },
      stock: 60,
      reviews: [],
    },
    {
      id: "b10",
      slug: "yves-saint-laurent-libre-edp-90ml",
      name: isEn ? "Libre Eau de Parfum Women 90ml" : "Libre Eau de Parfum Kadın Parfüm 90ml",
      brand: "Yves Saint Laurent",
      categorySlug: "beauty-care",
      subcategorySlug: "perfume",
      categoryName: isEn ? "Beauty & Personal Care" : "Kozmetik & Kişisel Bakım",
      storeName: isEn ? "Trend Fashion Store" : "Trend Fashion Mağazası",
      price: 4799.00,
      originalPrice: 5699.00,
      rating: 4.9,
      reviewCount: 1180,
      imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=600&q=80",
      galleryImages: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80"],
      badges: { bestseller: true, fastDelivery: true, freeShipping: true },
      attributes: { color: [] },
      description: isEn ? "Lavender orange blossom grand floral EDP." : "Fransız lavantası ve portakal çiçeğinin büyüleyici kadın parfümü.",
      specifications: { [isEn ? "Type" : "Tür"]: "EDP" },
      stock: 14,
      reviews: [],
    },
  ];
}

export async function fetchDbProducts(lang: Language = "tr"): Promise<DetailedProductMock[]> {
  try {
    const res = await fetch(`/api/products`, { cache: "no-store" });
    if (!res.ok) return getFullCatalog(lang);
    const data = await res.json();
    if (data.products && Array.isArray(data.products) && data.products.length > 0) {
      return data.products.map((p: any) => mapDbProductToMock(p, lang));
    }
  } catch (e) {}
  return getFullCatalog(lang);
}

export async function fetchDbProductBySlug(slug: string, lang: Language = "tr"): Promise<DetailedProductMock | null> {
  try {
    const res = await fetch(`/api/products?slug=${encodeURIComponent(slug)}`, { cache: "no-store" });
    if (res.ok) {
      const data = await res.json();
      if (data.product) return mapDbProductToMock(data.product, lang);
    }
  } catch (e) {}

  const catalog = getFullCatalog(lang);
  return catalog.find((p) => p.slug === slug) || null;
}
