"use client";

import { useEffect, useState } from "react";
import { ImageIcon, Plus, Save, Trash2, X } from "lucide-react";

interface Banner { id: string; titleTR?: string | null; titleEN?: string | null; imageUrlDesktop: string; targetValue: string; active: boolean; orderIndex: number }

const emptyBanner = { titleTR: "", titleEN: "", imageUrlDesktop: "", targetValue: "/", active: true, orderIndex: 0 };

export function BannerManager({ isEn }: { isEn: boolean }) {
  const [banners, setBanners] = useState<Banner[]>([]);
  const [editing, setEditing] = useState<Partial<Banner> | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); fetch("/api/cms/banners").then((res) => res.ok ? res.json() : { banners: [] }).then((data) => setBanners(data.banners || [])).finally(() => setLoading(false)); };
  useEffect(load, []);
  const save = async () => { if (!editing?.imageUrlDesktop || !editing.targetValue) return; setSaving(true); await fetch("/api/cms/banners", { method: editing.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); setEditing(null); setSaving(false); load(); };
  const remove = async (id: string) => { if (!window.confirm(isEn ? "Delete this banner?" : "Bu banner silinsin mi?")) return; await fetch(`/api/cms/banners?id=${id}`, { method: "DELETE" }); load(); };
  return <section className="shrink-0 border-b border-slate-200 bg-white px-5 py-3 shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xs font-black uppercase tracking-wide text-slate-800"><ImageIcon className="size-4 text-indigo-600" /> {isEn ? "Sponsor & campaign banners" : "Sponsor ve kampanya bannerları"}</h2><p className="mt-1 text-[11px] text-slate-500">{isEn ? "Manage the promotional surfaces shown on the storefront." : "Mağazada görünen promosyon alanlarını yönetin."}</p></div><button type="button" onClick={() => setEditing({ ...emptyBanner })} className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-2 text-[11px] font-black text-white hover:bg-indigo-500"><Plus className="size-3.5" /> {isEn ? "Add banner" : "Banner ekle"}</button></div>
    <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{loading ? <span className="text-xs text-slate-400">{isEn ? "Loading banners…" : "Bannerlar yükleniyor…"}</span> : banners.length === 0 ? <span className="text-xs text-slate-400">{isEn ? "No campaign banners yet." : "Henüz kampanya bannerı yok."}</span> : banners.sort((a, b) => a.orderIndex - b.orderIndex).map((banner) => <div key={banner.id} className="flex min-w-56 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-2"><img src={banner.imageUrlDesktop} alt={banner.titleTR || "Banner"} className="size-10 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-black">{isEn ? banner.titleEN || banner.titleTR : banner.titleTR || banner.titleEN}</p><p className="text-[10px] text-slate-500">{banner.active ? (isEn ? "Active" : "Aktif") : (isEn ? "Inactive" : "Pasif")}</p></div><button type="button" aria-label={isEn ? "Edit banner" : "Bannerı düzenle"} onClick={() => setEditing(banner)} className="text-xs font-bold text-indigo-600">{isEn ? "Edit" : "Düzenle"}</button><button type="button" aria-label={isEn ? "Delete banner" : "Bannerı sil"} onClick={() => remove(banner.id)} className="text-rose-500"><Trash2 className="size-3.5" /></button></div>)}</div>
    {editing && <div className="mt-3 rounded-xl border border-indigo-200 bg-indigo-50/60 p-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><input value={editing.titleTR || ""} onChange={(e) => setEditing({ ...editing, titleTR: e.target.value })} placeholder="Başlık TR" className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs" /><input value={editing.titleEN || ""} onChange={(e) => setEditing({ ...editing, titleEN: e.target.value })} placeholder="Title EN" className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs" /><input value={editing.imageUrlDesktop || ""} onChange={(e) => setEditing({ ...editing, imageUrlDesktop: e.target.value })} placeholder="Desktop image URL" className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs" /><input value={editing.targetValue || ""} onChange={(e) => setEditing({ ...editing, targetValue: e.target.value })} placeholder="Target URL" className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs" /><input type="number" value={editing.orderIndex || 0} onChange={(e) => setEditing({ ...editing, orderIndex: Number(e.target.value) })} placeholder="Order" className="rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs" /></div><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold text-slate-600"><X className="size-3.5" /> {isEn ? "Cancel" : "Vazgeç"}</button><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50"><Save className="size-3.5" /> {saving ? (isEn ? "Saving…" : "Kaydediliyor…") : (isEn ? "Save banner" : "Bannerı kaydet")}</button></div></div>}
  </section>;
}
